# Generated by Django 6.0.4 on 2026-06-01 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва курсу')),
                ('description', models.TextField(verbose_name='Короткий опис для лендингу')),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='Термін (код/слово)')),
                ('definition', models.TextField(verbose_name='Визначення / Пояснення')),
                ('category', models.CharField(blank=True, default='Базові поняття', max_length=50, verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Термін словника',
                'verbose_name_plural': 'Словник термінів',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Термін')),
                ('definition', models.TextField(verbose_name='Визначення')),
            ],
            options={
                'verbose_name_plural': 'Словник',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Номер уроку')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок сторінки')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='Головне фото уроку (Зображення 1 у Figma)')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_title', models.CharField(max_length=250, verbose_name='Заголовок секції')),
                ('block_text', models.TextField(verbose_name='Основний текст секції')),
                ('block_image', models.ImageField(blank=True, null=True, upload_to='lesson_blocks/', verbose_name='Додати зображення (якщо потрібно)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення (0, 1, 2...)')),
                ('block_layout', models.CharField(choices=[('layout-standard', 'Стандартний (Текст на всю ширину)'), ('layout-author', 'Картка автора (Фото ЛІВОРУЧ, текст праворуч)'), ('layout-history', 'Історичний блок (Текст ліворуч, фото праворуч)'), ('layout-full-image', 'Велике фото (Фото на всю ширину, текст знизу)')], default='layout-standard', max_length=50, verbose_name='Оберіть розташування елементів (Дизайн)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Блок контенту уроку',
                'verbose_name_plural': 'Конструктор сторінки (Додати блоки тексту/картинок)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Запитання')),
                ('option_a', models.CharField(max_length=100, verbose_name='Варіант А')),
                ('option_b', models.CharField(max_length=100, verbose_name='Варіант Б')),
                ('option_v', models.CharField(blank=True, max_length=100, null=True, verbose_name="Варіант В (необов'язково)")),
                ('option_g', models.CharField(blank=True, max_length=100, null=True, verbose_name="Варіант Г (необов'язково)")),
                ('correct_option', models.CharField(choices=[('a', 'А'), ('b', 'Б'), ('v', 'В'), ('g', 'Г')], max_length=1, verbose_name='Правильна відповідь')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проходження')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Пройдений урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Прогрес користувача',
                'verbose_name_plural': 'Прогрес користувачів',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
