# Generated by Django 6.0.4 on 2026-06-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='author_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст про автора'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='history_text',
            field=models.TextField(blank=True, null=True, verbose_name='Історія'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='intro_text',
            field=models.TextField(blank=True, null=True, verbose_name='Вступний текст'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='Головне фото уроку'),
        ),
    ]
