# Generated by Django 6.0.4 on 2026-06-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_author_text_lesson_history_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='author_text',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='history_text',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='intro_text',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='main_image',
        ),
    ]
