# Generated by Django 6.0.4 on 2026-06-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lessons_completed',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='courses.lesson'),
        ),
    ]
